repos:
  - repo: local
    hooks:
      - id: go-fmt-check
        name: go fmt check
        entry: make fmt-check
        language: system
        pass_filenames: false
      - id: go-vet
        name: go vet
        entry: make vet
        language: system
        pass_filenames: false
      - id: go-test
        name: go test
        entry: make test
        language: system
        pass_filenames: false
